# Generated by Django 5.0 on 2023-12-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('origin', models.CharField(max_length=155)),
                ('orders', models.IntegerField(max_length=155, null=True)),
                ('lead_time', models.TimeField(max_length=155, null=True)),
            ],
        ),
    ]
